chatgpt_django_app/chat/urls.py
from django.urls import path

from .views import (
    index_view,
    message_list_view,
    message_create_view,
)

app_name = "chat"

urlpatterns = [
    path("chat/", index_view, name="index"),
    path("chat/<int:chat_pk>/message/list/", message_list_view, name="message-list"),
    path("chat/<int:chat_pk>/message/create/", message_create_view, name="message-create"),
]

chatgpt_django_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("chatgpt_django_app.chat.urls")),
    path('admin/', admin.site.urls),
]

chatgpt_django_app/chat/models.py
from django.db import models


class Chat(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]


class Message(models.Model):
    SYSTEM = 0
    ASSISTANT = 10
    USER = 20
    ROLE_CHOICES = (
        (SYSTEM, "System"),
        (ASSISTANT, "Assistant"),
        (USER, "User"),
    )

    role = models.IntegerField(choices=ROLE_CHOICES)
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE, related_name="messages")
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_at"]

    @property
    def role_label(self):
        role_label = self.get_role_display()
        return role_label

    @classmethod
    def for_openai(cls, messages):
        return [
            {"role": message.role_label.lower(), "content": message.content}
            for message in messages
        ]

chatgpt_django_app/chat/forms.py
from django import forms
from django.core.validators import MinLengthValidator

from .models import Chat, Message


class MessageForm(forms.ModelForm):
    content = forms.CharField(
        label='Content',
        widget=forms.Textarea(
            attrs={
                'rows': 5,
                'class': "rounded-lg border-gray-300 block leading-normal border px-4 text-gray-700 bg-white "
                         "focus:outline-none py-2 appearance-none w-full",
                'data-controller': "textarea-autogrow",
                "placeholder": "Ctrl + Enter to send",
            },
        ),
        validators=[MinLengthValidator(2)]
    )

    class Meta:
        model = Message
        fields = ("content",)

    def __init__(self, *args, **kwargs):
        self.role = kwargs.pop("role")
        self.chat_pk = kwargs.pop("chat_pk")

        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.chat_id = self.chat_pk
        instance.role = self.role
        if commit:
            instance.save()
        return instance

chatgpt_django_app/chat/views.py
from django.urls import reverse
from django.views import View
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.http import HttpResponseRedirect
from turbo_helper import turbo_stream

from .models import Chat, Message
from .forms import MessageForm


class IndexView(View):

    def get(self, request):
        # If no chat exists, create a new chat and redirect to the message list page.
        chat = Chat.objects.first()
        if not chat:
            chat = Chat.objects.create()
        return HttpResponseRedirect(reverse("chat:message-list", args=[chat.pk]))

    def post(self, request, *args, **kwargs):
        # create new chat object and redirect to message list view
        instance = Chat.objects.create()
        return HttpResponseRedirect(reverse("chat:message-list", args=[instance.pk]))


index_view = IndexView.as_view()


class MessageListView(ListView):
    model = Message
    template_name = "message_list_page.html"

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(chat_id=self.kwargs["chat_pk"])
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["chats"] = Chat.objects.all()
        return context


message_list_view = MessageListView.as_view()


class MessageCreateView(CreateView):
    model = Message
    template_name = "message_create.html"
    form_class = MessageForm

    def get_success_url(self):
        return None

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["chat_pk"] = self.kwargs.get("chat_pk")
        kwargs["role"] = Message.USER
        return kwargs

    def get_empty_form(self):
        """
        Return empty form so we can reset the form
        """
        form_class = self.get_form_class()
        kwargs = self.get_form_kwargs()
        kwargs.pop("data")
        kwargs.pop("files")
        kwargs.pop("instance")
        return form_class(**kwargs)

    def form_valid(self, form):
        super().form_valid(form)

        return turbo_stream.response(
            turbo_stream.replace(
                "message_create",
                template=self.template_name,
                context={
                    "form": self.get_empty_form(),
                    "view": self,
                },
                request=self.request,
            ),
        )


message_create_view = MessageCreateView.as_view()

chatgpt_django_app/templates/base.html
{% load webpack_loader static %}

<!DOCTYPE html>
<html>
<head>
  <title>ChatGPT Demo</title>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  {% stylesheet_pack 'app' %}
  {% javascript_pack 'app' attrs='defer' %}
</head>

<body data-turbo="false">

{% block content %}
{% endblock %}

</body>
</html>

chatgpt_django_app/templates/message_create.html
{% load turbo_helper %}

{% turbo_frame "message_create" data_turbo="true" %}

  <form
    method="post"
    action="{% url 'chat:message-create' view.kwargs.chat_pk %}"
    class="p-2 m-2"
    data-controller="chatgpt-message-form"
    data-action="keydown.ctrl+enter->chatgpt-message-form#autoSubmit focusin->chatgpt-message-form#scroll"
    data-chatgpt-message-form-target-value="{% dom_id view.kwargs.chat_pk "message_list_container" %}"
  >
    {% csrf_token %}

    <div class="mb-3">
      {{ form.content }}

      <div class="text-xs italic text-red-500">
        {{ form.content.errors }}
      </div>
    </div>

    <button type="submit"
            class="transition-all bg-blue-500 hover:bg-blue-600 text-white py-2 px-4 rounded disabled:bg-gray-400 disabled:text-gray-500 disabled:cursor-not-allowed"
            data-turbo-submits-with="Submitting..."
    >
      Submit
    </button>

  </form>

{% endturbo_frame %}

chatgpt_django_app/templates/message_item.html
{% load turbo_helper %}

<div id="message_{{ instance.pk }}">
  {% if instance.role_label == 'User' %}
    <div class="p-4 m-4 max-w-full text-black rounded-lg bg-sky-100 prose"
         data-controller="message"
         data-content="{{ instance.content|escape }}"
         data-message-target-value="{% dom_id instance.chat_id "message_list" %}"
         data-turbo-stream="{{ request|yesno:"false,true" }}"
    >
    </div>
  {% else %}
    <div class="p-4 m-4 max-w-full bg-gray-200 rounded-lg prose"
         data-controller="message"
         data-content="{{ instance.content|escape }}"
         data-message-target-value="{% dom_id instance.chat_id "message_list" %}"
         data-turbo-stream="{{ request|yesno:"false,true" }}"
    >
    </div>
  {% endif %}
</div>

chatgpt_django_app/templates/message_list.html
{% load turbo_helper %}
<div id="{% dom_id chat_pk "message_list" %}">
  {% for instance in object_list %}
    {% include "message_item.html" with instance=instance %}
  {% endfor %}
</div>

chatgpt_django_app/templates/message_list_page.html
{% extends "base.html" %}

{% load turbo_helper %}

{% block content %}

  <main class="w-full">
    <div class="grid grid-cols-12 gap-2">
      <div class="col-span-12 bg-gray-50 sm:col-span-3">
        <div class="flex flex-col space-y-1 sm:h-screen">

          <form method="post" action="{% url 'chat:index' %}">
            {% csrf_token %}
            <button type="submit" class="bg-green-500 text-white py-2 px-4 rounded m-2">Start a new conversation</button>
          </form>

          <ul class="flex flex-col py-4 space-y-2">
            {% for chat in chats %}
              <a class="text-white py-2 px-2 rounded mx-2 bg-blue-500"
                 href="{% url 'chat:message-list' chat.pk %}">Chat: created on <time>{{ chat.created_at }}</time></a>
            {% endfor %}
          </ul>

        </div>
      </div>
      <div class="col-span-12 bg-gray-50 sm:col-span-9">
        <div class="bg-gray-50 sm:h-screen">

          <div class="flex flex-col h-full">

            <!-- Subscribe to the chat group, so we can send Turbo stream via Websocket -->
            <!-- https://django-turbo-helper.readthedocs.io/en/latest/real-time-updates.html -->
            {% turbo_stream_from 'chat' view.kwargs.chat_pk %}

            <div class="overflow-y-auto flex-1" id="{% dom_id view.kwargs.chat_pk "message_list_container" %}">
              {% include 'message_list.html' with chat_pk=view.kwargs.chat_pk %}
            </div>

            <div class="p-2">
              {% url 'chat:message-create' view.kwargs.chat_pk as src %}
              {% turbo_frame "message_create" src=src data_turbo="true" %}
                Loading...
              {% endturbo_frame %}
            </div>

          </div>

        </div>
      </div>
    </div>
  </main>

{% endblock %}